### ISSUE TITLE
Support configuration of anonymization parameters

### ISSUE THREAD

**Issue by cristianberneanu** [diffix/desktop#249]
We need to first decide which parameters makes sense to expose and where to place them.
Then we need to update the service request structures.

**Comment by yoid2000** [comment]
The most important parameter is `low_thresh`. (This is somewhat analogous to `k` in k-anonymity.) If set to `low_thresh=2`, the minimum, then you can have a situation where banking account numbers for joint accounts (husband and wife) are shown (and the protected entity is the individual, not the bank account). That is why the default is `low_thresh=3`, but a user may well want to increase this a little.

The next most important parameter is `base_sd`. 

I think it might be good to make these two parameters pretty easy to change, and then hide the other parameters behind some 'more settings' kind of button.

`low_thresh` can be an integer, and it is easy to imagine some kind of counter with a `+` and `-` symbol of some sort to increase and decrease.

`base_sd` is not an integer, but we could have pre-set settings like 1.5, 2, 2.5, 3, 4, 5 ....

**Comment by yoid2000** [comment]
Here is a table showing the parameters and reasonable pre-set values:

| parameter | values | notes |
| --- | --- | --- |
| `low_thresh` | 2,3,4,5,... | hard suppression threshold |
| `sd_supp` | 1.0,1.2,1.4,1.8,2.0,... |  |
| `low_mean_gap` | 2,2.5,3,... |  |
| `base_sd` | 1.5, 2, 2.5, 3, 4, 5, ... |  |
| `outlier_min` | 1,2,3... | min number entities in outlier_group |
| `outlier_width` | 1,2,3,, ... | `outlier_max` = `outlier_min`+`outlier_width` |
| `top_min` | 2,3,4,... | min number entities in top_group |
| `top_width` | 1,2,3,, ... | `top_max` = `top_min`+`top_width` |

**Comment by yoid2000** [comment]
Maybe a good widget for all of the above is a text box with adjoining up and down arrows. The arrows step through the pre-set values, but there is always the option of just typing a number into the text box. 

![image](https://user-images.githubusercontent.com/2162345/141962755-d063582a-809e-4125-ad88-7669ac94f01c.png)

![image](https://user-images.githubusercontent.com/2162345/141962871-d464ab4a-c4e6-4649-b999-419dae93d606.png)

**Comment by yoid2000** [comment]
We will have three settings, P, XP, and XXP. The switch/slider for these settings can probably be positioned right below the columns selection window (but could also go above). The switch/slider can be labeled "Anonymization Strength". Open to other suggestions.

The default setting is P.

Changing the setting causes the current query to be re-executed, but with the new setting.

The settings are as follows:

| parameter | P | XP | XXP |
| --- | --- | --- | --- |
| `low_thresh` | 3 | 4 | 5 |
| `sd_supp` | 1.0 | 1.0 | 1.0 |
| `low_mean_gap` | 2 | 2 | 2 |
| `base_sd` | 1.5 | 2.25 | 3.0 |
| `outlier_min` | 1 | 2 | 2 |
| `outlier_max` | 2 | 3 | 3 |
| `top_min` | 3 | 3 | 3 |
| `top_max` | 4 | 4 | 4 |

Also needed:

Documentation about the values (Paul)
Another item in the left-side navigation panel (Edon)
