### ISSUE TITLE
LED causes long Preview request when there are ~40k buckets

### ISSUE THREAD

**Issue by pdobacz** [diffix/desktop#272]
This is caused by `reference` but the steps to reproduce are easiest with `desktop` so filing here.

Steps:

With commandline (customize your path to the CSV):
```
echo '{"type":"Preview","inputPath":"/home/user/sources/opendiffix/data/taxi-one-day.csv","aidColumn":"\"hack\"","salt":"c5196322011d8f4acaf8db2358b81bf4fab34dd243f9d12c189f0bfda8476412","anonParams":{"suppression":{"lowThreshold":3,"sD":1,"lowMeanGap":2},"outlierCount":{"lower":1,"upper":2},"topCount":{"lower":3,"upper":4},"baseNoiseSD":1.5},"buckets":["\"dropoff_latitude\""],"countInput":"Rows","rows":1000}' | dotnet run --project anonymizer/OpenDiffix.Service
```

for gui steps are:
1/ load taxi-one-day.csv data set
2/ `hack` as AID
3/ `dropoff_lattitude` as bucket

**Comment by cristianberneanu** [comment]
So this never finishes or it just takes a very long time?
And it doesn't happen with the beta release? In that case it, might be related to LED (which is handled by the service).

**Comment by edongashi** [comment]
> just takes a very long time

This. The code is just nested `Array.iter`s so no way for it to get stuck. But with `O(n^2)` complexity and hundreds of thousands of buckets it takes an absurd amount of time.

**Comment by yoid2000** [comment]
> I have a more performant idea in mind.

which is? (there are probably some heuristics we could use to eliminate much of the search...)

**Comment by edongashi** [comment]
> which is? (there are probably some heuristics we could use to eliminate much of the search...)

Comparing against a subset of buckets by holding indexes of buckets per column value (hash table). Then we revert to your initial algorithm of going through every column and comparing against all other buckets (by picking them from other columns' indexes).

**Comment by yoid2000** [comment]
A super-efficient heuristic would be that any index with more than, say, 10 values is almost certainly not going to be an isolating column. As the number of distinct values goes up, the probability that it serves as an isolating column quickly goes down.

**Comment by edongashi** [comment]
Ok, in that case we can abort building an index when it goes above the threshold and ignore in `buckets_to_compare`.

**Comment by yoid2000** [comment]
thinking a bit more ...

I pushed the latest version of the elm spec to https://github.com/diffix/internal-strategy/tree/main/resources/docs

There is a sub-section inside section 5.10 labeled "Evaluation of likelihood that table conditions exist"

This shows that a column really only works as an isolating column when some value dominates. In other words, there can be some number of distinct values, but only if one or two of the values dominates does the problem occur.

Below is data I generated for the taxi dataset. This lists the columns that worked as isolating columns. (This can be found here: https://github.com/diffix/attacker/blob/main/diffixElmPaperAttacks/findConditions/findConditionsResults.taxi.csv.json)

There are six columns that worked as isolating columns.

Of these, the column with the most distinct values is `rate_code` with seven values. Note, however, that of these seven, one value dominates. `payment_type` has five values, but two dominate.

So, rather than say that columns with more than 10 values are almost certainly not isolating, we can say that only columns where 1 to 3 distinct values dominate can really be isolating columns.

I'll make this more concrete in the following comment.

```
        "isolatingColumnProfile": {
            "mta_tax": [
                [
                    0.0,
                    1118
                ],
                [
                    0.5,
                    12989
                ]
            ],
            "payment_type": [
                [
                    "CRD",
                    12917
                ],
                [
                    "CSH",
                    12918
                ],
                [
                    "DIS",
                    213
                ],
                [
                    "NOC",
                    619
                ],
                [
                    "UNK",
                    84
                ]
            ],
            "rate_code": [
                [
                    0,
                    15
                ],
                [
                    1,
                    12979
                ],
                [
                    2,
                    4442
                ],
                [
                    3,
                    391
                ],
                [
                    4,
                    523
                ],
                [
                    5,
                    1030
                ],
                [
                    6,
                    10
                ]
            ],
            "sf_flag": [
                [
                    null,
                    6634
                ],
                [
                    "N",
                    6374
                ],
                [
                    "Y",
                    2158
                ]
            ],
            "surcharge": [
                [
                    0.0,
                    12565
                ],
                [
                    0.5,
                    11878
                ],
                [
                    1.0,
                    12020
                ],
                [
                    1.5,
                    12
                ],
                [
                    2.0,
                    1
                ],
                [
                    3.0,
                    1
                ]
            ],
            "vendor_id": [
                [
                    "CMT",
                    6375
                ],
                [
                    "VTS",
                    6621
                ]
            ]
        },
```

**Comment by yoid2000** [comment]
I think a good heuristic is this:

The only columns that can be isolating columns are columns where:

1. One distinct value has at least 60% of all rows (or AIDVs)
2. Two distinct values each have at least 30% of all rows (or AIDVs)
3. Three distinct values each have at least 20% of all rows (or AIDVs)

I think anything else will almost never work as an isolating column.

So the question is, is there a simple way to detect the above and abort the algorithm early?

**Comment by edongashi** [comment]
Led is very fast now. Closing as fixed.
