### ISSUE TITLE
Modification to Desktop-settable anonymization parameters

### ISSUE THREAD

**Issue by yoid2000** [diffix/desktop#273]
Having completed the analysis for the Elm doc, I'm now of the strong opinion that the only really important anonymization parameter we need to expose in Desktop is `low_thresh`.

So instead of the `P`, `XP`, `XXP` family of settings, I propose a setting which we can call "Suppression Threshold" (which internally maps to `low_thresh`).

The default would be 3 (meaning that buckets with 2 or 1 AIDV are suppressed, but 3 may not be suppressed).

I would like the minimum to be 2. I don't see a need for a maximum (though in practice 10 or higher would be pretty excessive).

Maybe this kind of thing:
![image](https://user-images.githubusercontent.com/2162345/144036245-19d6c5e0-afae-435d-bad1-da1a2ef37cba.png)

**Comment by cristianberneanu** [comment]
> So instead of the P, XP, XXP family of settings, I propose a setting which we can call "Suppression Threshold"

It would be simpler to understand the effect of the setting. We should also make the same simplification in the paper.

**Comment by yoid2000** [comment]
> It would be simpler to understand the effect of the setting

I'm not sure what you mean by this.

> We should also make the same simplification in the paper.

The P, XP, XXP stuff in the paper is really an experimental convenience: it is a way of reducing the explored parameter space so that we don't have an exponential of settings to try....

**Comment by cristianberneanu** [comment]
I meant that is easier to understand the effect of changing the suppression threshold, rather than understand the effect of changing the preset from `P` to `XP` or `XPP`.

**Comment by yoid2000** [comment]
> I meant that is easier to understand the effect of changing the suppression threshold

Ah, you were agreeing with me!  Good  ;)
