### ISSUE TITLE
Suppression threshold is a controlled input but has a defaultValue

### ISSUE THREAD

**Issue by edongashi** [diffix/desktop#279]
`defaultValue` and `value` cannot coexist.

**Comment by pdobacz** [comment]
is this actually causing an issue? I started off without `defaultValue` and it didn't work

**Comment by pdobacz** [comment]
hm, I now see that a similar thing works in the column selection step, I'll take a look

**Comment by pdobacz** [comment]
ah ok, I see. `Substring start` uses a placeholder, not a real value, to display the default "1". I'll fix this using that, but let me know, if I'm off the scent.

**Comment by edongashi** [comment]
`src/AnonParamsSelectionStep/AnonParamsSelectionStep.tsx` in L47-48.

`value` makes an input [controlled](https://reactjs.org/docs/forms.html#controlled-components), while `defaultValue is for [uncontrolled](https://reactjs.org/docs/uncontrolled-components.html). `defaultValue` has no effect and should be removed.

**Comment by pdobacz** [comment]
@edongashi pls see my comments above. Without `defaultValue` it just plain doesn't work, the box is empty on first render and if you click ^/v it will start from the minimum 2, not the default 3. (to be honest, I just checked and with `placeholder` it also behaves funky, if you click ^ it will go from `3` down to `2`).

I'll be looking for a proper solution. Actually, what works is to remove `value`, but this seems not recommended

**Comment by edongashi** [comment]
I could be wrong, I just saw a react warning in the dev console and may have associated it incorrectly. Let me take this issue while you focus on the other one?

**Comment by pdobacz** [comment]
I think the warning might be correct, as we're doing something messy (value and defaultValue), but the most proper and recommended way doesn't seem to work.

But don't worry, I already did some research and can poke around this some more, so you can also focus on the LED optimizations. I think right now, things work correctly but are just messy, so we can fix this later. Also - this code is moving in the other PR, so easier to fix after it had moved.
