### ISSUE TITLE
Change "Adjust suppression threshold" to just "Suppression threshold"

### ISSUE THREAD

**Issue by yoid2000** [diffix/desktop#285]
The default of 3 normally doesn't have to be adjusted, so I'd like to remove "Adjust" from the heading so that there is no implication that it needs to be done.

**Comment by cristianberneanu** [comment]
If we integrate the suppression threshold control into the AID selection step, than the heading goes away entirely.

**Comment by yoid2000** [comment]
I'm not sure we are going to integrate it with AID selection so much as place it next to AID selection. Regardless, we need to somehow make it clear that AID selection is required and suppression threshold is optional (and often if not usually unnecessary)
